/**
 * ServicesData.js
 * ===============
 * Centralized registry of all 15 services offered by Financially Up Australia.
 * Contains metadata, categorization, scope highlights, search keywords, and routing paths.
 */

export const SERVICE_CATEGORIES = [
  { id: "all", label: "All Services", count: 15 },
  { id: "personal-tax", label: "Personal & Property Tax", count: 3 },
  { id: "business-tax", label: "Business & Corporate Tax", count: 3 },
  { id: "structures-wealth", label: "Structures, Trusts & Wealth", count: 3 },
  { id: "operations", label: "Bookkeeping & Operations", count: 2 },
  { id: "advisory-cfo", label: "Advisory & Virtual CFO", count: 3 },
  { id: "resolution", label: "Resolution & ATO Support", count: 1 },
];

export const SERVICES_LIST = [
  {
    id: "individual-tax",
    pillar: "Pillar 01",
    slug: "individual-tax",
    href: "/services/individual-tax",
    title: "Individual Tax Accounting",
    category: "personal-tax",
    tag: "Personal & Investors",
    description:
      "Expert tax return preparation for Australian wage earners, executives, property landlords, crypto traders, and multi-stream contractors.",
    highlights: [
      "Salary, wages & work deductions",
      "Rental properties & negative gearing",
      "Capital gains tax (CGT) & cryptocurrency",
      "Overdue returns & prior-year lodgements",
    ],
    icon: "wallet",
    accent: "emerald",
    keywords: [
      "individual tax",
      "personal tax",
      "tax return",
      "salary",
      "negative gearing",
      "crypto",
      "cgt",
      "mytax",
      "deductions",
      "work expenses",
      "sole trader",
    ],
  },
  {
    id: "business-tax",
    pillar: "Pillar 02",
    slug: "business-tax",
    href: "/services/business-tax",
    title: "Business Tax Accounting",
    category: "business-tax",
    tag: "Pty Ltd, Trusts & SMEs",
    description:
      "End-to-end tax returns, year-end accounts, and corporate compliance for proprietary companies, partnerships, trusts, and growing businesses.",
    highlights: [
      "Company tax returns & franking accounts",
      "Partnership & sole trader tax returns",
      "Division 7A loan agreements & compliance",
      "Year-end financial statements & balance sheets",
    ],
    icon: "bank",
    accent: "teal",
    keywords: [
      "business tax",
      "company tax",
      "pty ltd",
      "partnership",
      "sole trader",
      "division 7a",
      "corporate tax",
      "balance sheet",
      "financial statements",
    ],
  },
  {
    id: "tax-planning",
    pillar: "Pillar 03",
    slug: "tax-planning",
    href: "/services/tax-planning",
    title: "Tax Planning & Advisory",
    category: "advisory-cfo",
    tag: "Strategic Optimization",
    description:
      "Proactive pre-30 June tax reviews and strategic structuring to legally optimize tax liability, protect family assets, and plan distributions.",
    highlights: [
      "Pre-30 June annual tax projections",
      "Trust distribution resolutions & minutes",
      "Capital gains mitigation & timing",
      "Small business CGT concessions & restructuring",
    ],
    icon: "solution",
    accent: "cyan",
    keywords: [
      "tax planning",
      "pre 30 june",
      "trust distribution",
      "cgt concessions",
      "tax strategy",
      "tax minimization",
      "division 7a",
      "planning",
    ],
  },
  {
    id: "bookkeeping",
    pillar: "Pillar 04",
    slug: "bookkeeping",
    href: "/services/bookkeeping",
    title: "Bookkeeping Services",
    category: "operations",
    tag: "Day-to-Day Accounts",
    description:
      "Reliable day-to-day bookkeeping, cloud software management (Xero, MYOB), accounts reconciliation, and accurate monthly reporting.",
    highlights: [
      "Daily/weekly bank feed reconciliation",
      "Accounts payable & receivable management",
      "Cloud accounting setup (Xero, MYOB, QBO)",
      "Clean records ready for BAS and tax lodgement",
    ],
    icon: "calculator",
    accent: "blue",
    keywords: [
      "bookkeeping",
      "xero",
      "myob",
      "quickbooks",
      "bank reconciliation",
      "invoices",
      "accounts payable",
      "accounts receivable",
      "ledger",
    ],
  },
  {
    id: "bas-payroll",
    pillar: "Pillar 05",
    slug: "bas-payroll",
    href: "/services/bas-payroll",
    title: "BAS, GST & Payroll Services",
    category: "business-tax",
    tag: "Compliance & STP",
    description:
      "Punctual Business Activity Statement (BAS) lodgements, GST reconciliation, Single Touch Payroll (STP 2.0), and superannuation tracking.",
    highlights: [
      "Quarterly & monthly BAS / IAS lodgements",
      "GST reconciliations & input tax credits",
      "Single Touch Payroll (STP Phase 2) processing",
      "Superannuation Guarantee (SG) & payroll tax",
    ],
    icon: "audit",
    accent: "indigo",
    keywords: [
      "bas",
      "gst",
      "payroll",
      "ias",
      "stp",
      "single touch payroll",
      "superannuation",
      "activity statements",
      "ato reporting",
    ],
  },
  {
    id: "business-structures",
    pillar: "Pillar 06",
    slug: "business-structures",
    href: "/services/business-structures",
    title: "Business Structures & Setup",
    category: "structures-wealth",
    tag: "Foundation & Restructuring",
    description:
      "Strategic entity structuring across Companies, Family Trusts, Partnerships, and Sole Traders for asset protection and optimal tax efficiency.",
    highlights: [
      "Entity comparison (Company vs Trust vs Sole Trader)",
      "New company incorporation & ABN/TFN registrations",
      "Business restructuring & rollover relief",
      "Asset protection & founder equity frameworks",
    ],
    icon: "apartment",
    accent: "violet",
    keywords: [
      "business structure",
      "company setup",
      "family trust setup",
      "entity formation",
      "incorporation",
      "asset protection",
      "restructuring",
      "abn registration",
    ],
  },
  {
    id: "asic",
    pillar: "Pillar 07",
    slug: "asic",
    href: "/services/asic",
    title: "ASIC Compliance & Secretarial",
    category: "operations",
    tag: "Corporate Governance",
    description:
      "Complete corporate secretarial support, annual company reviews, solvency declarations, share transfers, and registered office management.",
    highlights: [
      "ASIC annual review statement lodgement",
      "Annual solvency resolutions for directors",
      "Director, secretary & shareholder changes",
      "Registered office & principal place of business maintenance",
    ],
    icon: "file-protect",
    accent: "amber",
    keywords: [
      "asic",
      "corporate secretarial",
      "annual review",
      "solvency resolution",
      "company director change",
      "share transfer",
      "asic registered agent",
    ],
  },
  {
    id: "trusts",
    pillar: "Pillar 08",
    slug: "trusts",
    href: "/services/trusts",
    title: "Trust Accounting & Tax",
    category: "structures-wealth",
    tag: "Family & Unit Trusts",
    description:
      "Specialist accounting, distribution planning, trustee minutes, Section 100A compliance, and annual tax returns for Australian trusts.",
    highlights: [
      "Discretionary, family & unit trust tax returns",
      "Pre-June 30 trustee distribution resolutions",
      "ATO Section 100A & Part IVA compliance guidance",
      "Corporate trustee setups & appointor changes",
    ],
    icon: "safety",
    accent: "emerald",
    keywords: [
      "trust accounting",
      "family trust",
      "unit trust",
      "discretionary trust",
      "trust tax return",
      "section 100a",
      "trustee resolution",
      "distributions",
    ],
  },
  {
    id: "smsf",
    pillar: "Pillar 09",
    slug: "smsf",
    href: "/services/smsf",
    title: "SMSF Accounting & Audit",
    category: "structures-wealth",
    tag: "Self-Managed Super",
    description:
      "End-to-end self-managed super fund accounting, annual financial statements, tax return lodgements, and independent audit facilitation.",
    highlights: [
      "Annual SMSF financial statements & member balances",
      "Fund tax return (SAR) preparation & lodgement",
      "Coordination of independent approved SMSF audit",
      "Pension phase, transfer balance cap & contribution caps",
    ],
    icon: "crown",
    accent: "teal",
    keywords: [
      "smsf",
      "self-managed super fund",
      "superannuation",
      "smsf tax return",
      "smsf audit",
      "pensions",
      "trustee compliance",
      "sar lodgement",
    ],
  },
  {
    id: "property-tax",
    pillar: "Pillar 10",
    slug: "property-tax",
    href: "/services/property-tax",
    title: "Property Tax Accounting",
    category: "personal-tax",
    tag: "Investors & Developers",
    description:
      "Specialized taxation support for residential and commercial landlords, property flippers, developers, and negative gearing investors.",
    highlights: [
      "Rental property schedules & expense deductions",
      "Capital Gains Tax (CGT) discount & 6-year absence rule",
      "Depreciation schedule integration (Division 40 & 43)",
      "Property developments, subdivisions & GST margin scheme",
    ],
    icon: "home",
    accent: "cyan",
    keywords: [
      "property tax",
      "rental property",
      "negative gearing",
      "cgt property",
      "depreciation schedule",
      "property development",
      "gst margin scheme",
      "subdivision",
    ],
  },
  {
    id: "ato-help",
    pillar: "Pillar 11",
    slug: "ato-help",
    href: "/services/ato-help",
    title: "ATO Help, Debt & Audit Support",
    category: "resolution",
    tag: "Resolution & Advocacy",
    description:
      "Professional advocacy and representation for ATO debt payment arrangements, penalty remissions, audit defense, and overdue returns.",
    highlights: [
      "ATO payment plans & debt negotiation",
      "Remission of General Interest Charge (GIC) & penalties",
      "ATO audit assistance & formal response letters",
      "Catch-up lodgement for multi-year overdue returns",
    ],
    icon: "shield",
    accent: "rose",
    keywords: [
      "ato help",
      "tax debt",
      "payment plan",
      "gic remission",
      "penalties",
      "ato audit",
      "overdue tax",
      "tax dispute",
      "director penalty notice",
    ],
  },
  {
    id: "business-advisory",
    pillar: "Pillar 12",
    slug: "business-advisory",
    href: "/services/business-advisory",
    title: "Business Advisory & Growth",
    category: "advisory-cfo",
    tag: "Strategy & Performance",
    description:
      "Commercial advisory services delivering financial visibility, KPI performance tracking, budgeting, forecasting, and expansion strategies.",
    highlights: [
      "Custom financial dashboards & KPI benchmarking",
      "Cash flow forecasting & dynamic budgeting models",
      "Profitability analysis & product/service pricing strategy",
      "Business valuation insights & succession planning",
    ],
    icon: "rise",
    accent: "orange",
    keywords: [
      "business advisory",
      "business advisor",
      "kpi",
      "budgeting",
      "forecasting",
      "profit margins",
      "growth strategy",
      "financial visibility",
    ],
  },
  {
    id: "virtual-cfo",
    pillar: "Pillar 13",
    slug: "virtual-cfo",
    href: "/services/virtual-cfo",
    title: "Virtual CFO Services",
    category: "advisory-cfo",
    tag: "Executive Finance",
    description:
      "Senior-level executive financial leadership on a flexible fractional basis—covering 3-way forecasting, board reporting, and capital strategy.",
    highlights: [
      "Fractional executive financial leadership",
      "3-way financial forecasting (P&L, balance sheet, cash flow)",
      "Board presentations & stakeholder reporting",
      "Capital raising, banking & investor relations support",
    ],
    icon: "line-chart",
    accent: "purple",
    keywords: [
      "virtual cfo",
      "fractional cfo",
      "cfo services",
      "3-way forecast",
      "cash flow modeling",
      "board reporting",
      "finance director",
    ],
  },
  {
    id: "international-tax",
    pillar: "Pillar 14",
    slug: "international-tax",
    href: "/services/international-tax",
    title: "International Tax Accounting",
    category: "personal-tax",
    tag: "Cross-Border & Expats",
    description:
      "Navigating Australian tax residency, foreign income, overseas pensions, expat filings, and double tax agreement (DTA) foreign tax offsets.",
    highlights: [
      "Australian tax residency status determinations",
      "Foreign source income & Foreign Income Tax Offsets (FITO)",
      "Australian expat tax returns & non-resident lodgements",
      "Foreign pensions, investments & cross-border withholding",
    ],
    icon: "global",
    accent: "sky",
    keywords: [
      "international tax",
      "expat tax",
      "foreign income",
      "residency",
      "fito",
      "double tax agreement",
      "non resident tax",
      "overseas pensions",
    ],
  },
  {
    id: "rd-tax-incentive",
    pillar: "Pillar 15",
    slug: "rd-tax-incentive",
    href: "/services/rd-tax-incentive",
    title: "R&D Tax Incentive Consulting",
    category: "business-tax",
    tag: "Innovation & Offsets",
    description:
      "Unlock government tax offsets for Australian innovation—assessing eligibility, documentation, AusIndustry registration, and company tax claims.",
    highlights: [
      "Core vs supporting R&D activity eligibility assessments",
      "Eligible expenditure tracking & contractor apportionment",
      "AusIndustry annual application & registration filing",
      "Company tax return R&D Schedule 15 preparation (refundable offset)",
    ],
    icon: "experiment",
    accent: "emerald",
    keywords: [
      "r&d tax incentive",
      "research and development",
      "ausindustry",
      "refundable tax offset",
      "innovation",
      "schedule 15",
      "eligible expenditure",
    ],
  },
];

/**
 * Client persona pathways for targeted recommendation
 */
export const CLIENT_PERSONAS = [
  {
    id: "wage-earners",
    title: "Individuals & Wage Earners",
    subtitle: "Maximise eligible deductions & simplify tax season",
    badge: "Personal",
    icon: "user",
    description:
      "Ideal for professionals, salary earners, remote workers, and multi-income households wanting fast, accurate, and stress-free ATO returns.",
    recommendedSlugs: ["individual-tax", "property-tax", "tax-planning"],
  },
  {
    id: "sole-traders",
    title: "Sole Traders & Contractors",
    subtitle: "Balance ABN growth with complete tax clarity",
    badge: "Sole Trader",
    icon: "tool",
    description:
      "For independent contractors, freelancers, and tradespeople needing combined personal and business tax, BAS reporting, and write-off advice.",
    recommendedSlugs: ["individual-tax", "bas-payroll", "bookkeeping"],
  },
  {
    id: "pty-ltd",
    title: "Small to Medium Companies",
    subtitle: "Complete compliance, BAS, payroll & year-end accounts",
    badge: "Pty Ltd & SME",
    icon: "bank",
    description:
      "For Australian proprietary limited entities requiring reliable corporate returns, Division 7A planning, ASIC governance, and payroll.",
    recommendedSlugs: [
      "business-tax",
      "bas-payroll",
      "asic",
      "bookkeeping",
    ],
  },
  {
    id: "property-investors",
    title: "Property Investors & Developers",
    subtitle: "Strategic deductions, negative gearing & CGT rules",
    badge: "Property & Wealth",
    icon: "home",
    description:
      "For landlords holding residential or commercial portfolios, property renovators, and developers managing GST margin scheme requirements.",
    recommendedSlugs: [
      "property-tax",
      "tax-planning",
      "business-structures",
    ],
  },
  {
    id: "trusts-smsf",
    title: "Trustees & SMSF Custodians",
    subtitle: "Fiduciary compliance, annual accounts & audit",
    badge: "Trusts & Super",
    icon: "crown",
    description:
      "For family discretionary trusts, unit trusts, and self-managed super funds needing statutory tax returns, minutes, and independent audits.",
    recommendedSlugs: ["trusts", "smsf", "tax-planning"],
  },
  {
    id: "growth-scaleups",
    title: "High-Growth Scaleups & Executives",
    subtitle: "Commercial forecasting, CFO insights & R&D grants",
    badge: "Scaleup & Strategy",
    icon: "rise",
    description:
      "For expanding companies requiring high-level Virtual CFO leadership, 3-way financial modeling, growth advisory, and R&D tax incentives.",
    recommendedSlugs: [
      "virtual-cfo",
      "business-advisory",
      "rd-tax-incentive",
    ],
  },
];
