"use client";

import React from "react";
import {
  BarChartOutlined,
  DollarOutlined,
  PercentageOutlined,
  TeamOutlined,
  PieChartOutlined,
  ClockCircleOutlined,
  RiseOutlined,
  SearchOutlined,
  CheckSquareOutlined,
  SyncOutlined,
  AuditOutlined,
} from "@ant-design/icons";

/**
 * ManagementReportingDecisions Component
 * =====================================
 * Section 6: Management reporting that supports decisions.
 *
 * Implements 100% verbatim content from '13th Pillar Virtual CFO.docx' (Section 1 - Virtual CFO).
 * Highlights decision-focused indicators (revenue by service line, gross margin, labour cost ratios,
 * customer concentration, debtor days, operating cash flow) and the 4-step repeatable management cycle.
 *
 * Background: Lite Brand Gradient.
 */
export default function ManagementReportingDecisions() {
  /**
   * The 6 performance indicators cited verbatim in Paragraph 1
   */
  const indicators = [
    {
      icon: <DollarOutlined className="text-xl text-teal-600 dark:text-teal-400" />,
      title: "Revenue by Service Line",
      description: "Dissecting which product offerings or practice departments generate profitable income.",
    },
    {
      icon: <PercentageOutlined className="text-xl text-emerald-600 dark:text-emerald-400" />,
      title: "Gross Margin",
      description: "Monitoring gross profitability after direct production and delivery costs.",
    },
    {
      icon: <TeamOutlined className="text-xl text-blue-600 dark:text-blue-400" />,
      title: "Labour Cost Ratios",
      description: "Evaluating payroll efficiency and staffing expenditure as a percentage of revenue.",
    },
    {
      icon: <PieChartOutlined className="text-xl text-purple-600 dark:text-purple-400" />,
      title: "Customer Concentration",
      description: "Tracking reliance on key accounts and revenue exposure across client tiers.",
    },
    {
      icon: <ClockCircleOutlined className="text-xl text-amber-600 dark:text-amber-400" />,
      title: "Debtor Days",
      description: "Measuring average collection turnaround and accelerating customer invoice payments.",
    },
    {
      icon: <RiseOutlined className="text-xl text-rose-600 dark:text-rose-400" />,
      title: "Operating Cash Flow",
      description: "Monitoring actual cash generated by day-to-day trading activities before financing.",
    },
  ];

  /**
   * The 4-step repeatable management process cited verbatim in Paragraph 2
   */
  const processSteps = [
    {
      step: "01",
      icon: <AuditOutlined className="text-xl text-teal-600 dark:text-teal-400" />,
      title: "Review the Numbers",
      description: "Examine profit and loss statements, balance sheets, cash flow statements and budgets.",
    },
    {
      step: "02",
      icon: <SearchOutlined className="text-xl text-blue-600 dark:text-blue-400" />,
      title: "Investigate Movements",
      description: "Identify why margins shifted, overheads changed, or cash timing varied from expectations.",
    },
    {
      step: "03",
      icon: <CheckSquareOutlined className="text-xl text-emerald-600 dark:text-emerald-400" />,
      title: "Agree Actions",
      description: "Determine concrete operational adjustments, pricing revisions, or cost controls.",
    },
    {
      step: "04",
      icon: <SyncOutlined className="text-xl text-purple-600 dark:text-purple-400" />,
      title: "Track the Result",
      description: "Monitor execution and measure outcomes in the subsequent monthly reporting cycle.",
    },
  ];

  return (
    <section className="py-16 sm:py-24 bg-gradient-to-b from-brand-bg-lighter via-white to-brand-bg-lighter/40 dark:from-zinc-900/60 dark:via-zinc-950 dark:to-zinc-900/40 relative border-b border-slate-200/80 dark:border-zinc-800 transition-colors">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-14">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-teal-50 dark:bg-teal-950/40 border border-teal-200/80 dark:border-teal-800/60 mb-4">
            <BarChartOutlined className="text-teal-600 dark:text-teal-400 text-xs sm:text-sm" />
            <span className="text-xs font-semibold text-teal-800 dark:text-teal-300 tracking-wide uppercase">
              Actionable Commercial Intelligence
            </span>
          </div>

          {/* Exact H2 Heading from Document */}
          <h2 className="text-2xl sm:text-3xl lg:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            Management reporting that supports decisions
          </h2>

          {/* Exact Verbatim Paragraph 1 from Document */}
          <p className="mt-4 text-base sm:text-lg text-slate-600 dark:text-zinc-300 leading-relaxed font-normal">
            Useful management reporting goes beyond printing a profit and loss statement. The aim is to focus attention on the numbers that explain performance. Depending on the business, that may include revenue by service line, gross margin, labour cost ratios, customer concentration, debtor days, operating cash flow or other meaningful indicators.
          </p>
        </div>

        {/* 6 Meaningful Indicators Cards Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 sm:gap-6 mb-14">
          {indicators.map((item, idx) => (
            <div
              key={idx}
              className="p-6 rounded-2xl bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 hover:border-teal-500/50 shadow-xs hover:shadow-md transition-all duration-300 flex flex-col justify-between group"
            >
              <div>
                <div className="w-12 h-12 rounded-xl bg-slate-50 dark:bg-zinc-800 flex items-center justify-center mb-4 group-hover:scale-105 transition-transform">
                  {item.icon}
                </div>
                <h3 className="text-base font-bold text-slate-900 dark:text-white mb-2">
                  {item.title}
                </h3>
                <p className="text-xs sm:text-sm text-slate-600 dark:text-zinc-400 leading-relaxed m-0 font-normal">
                  {item.description}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* 4-Step Repeatable Management Process (Exact Verbatim Paragraph 2) */}
        <div className="rounded-2xl bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 shadow-xs p-6 sm:p-8 lg:p-10">
          <div className="text-center max-w-3xl mx-auto mb-10 space-y-3">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-md bg-teal-50 dark:bg-teal-950/40 text-teal-700 dark:text-teal-300 text-xs font-semibold">
              <SyncOutlined />
              <span>A Repeatable Management Process</span>
            </div>
            {/* Exact Verbatim Paragraph 2 from Document */}
            <p className="text-sm sm:text-base text-slate-600 dark:text-zinc-300 leading-relaxed font-normal m-0">
              Government business guidance recommends reviewing key financial documents such as profit and loss statements, balance sheets, cash flow statements and budgets regularly. A virtual CFO helps turn those reports into a repeatable management process: review the numbers, investigate movements, agree actions and track the result.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {processSteps.map((step, idx) => (
              <div
                key={idx}
                className="p-5 rounded-xl bg-slate-50 dark:bg-zinc-950/60 border border-slate-200/80 dark:border-zinc-800/80 relative"
              >
                <div className="flex items-center justify-between mb-3">
                  <div className="w-10 h-10 rounded-lg bg-white dark:bg-zinc-800 flex items-center justify-center shadow-2xs">
                    {step.icon}
                  </div>
                  <span className="text-xs font-bold text-teal-600 dark:text-teal-400 font-mono">
                    {step.step}
                  </span>
                </div>
                <h4 className="text-sm font-bold text-slate-900 dark:text-white mb-1.5">
                  {step.title}
                </h4>
                <p className="text-xs text-slate-600 dark:text-zinc-400 leading-relaxed m-0 font-normal">
                  {step.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
